import Navigation from "../components/Navigation"
import '../../index.css'

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en"
    cz-shortcut-listen="true"
    >
      <body>
        <Navigation></Navigation>
        {children}
        </body>
    </html>
  )
}
