import Navigation from "../components/Navigation"
import '../../index.css'
import NoiseOverlay from "../components/NoiseOverlay/NoiseOverlay"

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en"
    cz-shortcut-listen="true"
    >
      <body className="flex flex-col h-screen relative">
        {/* <NoiseOverlay/> */}
        <div className="my-2">
          <Navigation></Navigation>
        </div>
        <main className="grow">
          {children}
        </main>
      </body>
    </html>
  );
}
